#!/usr/bin/python
import sys
from prettytable import PrettyTable
from cssefclient.cssefclient import *

class ArgumentParser(object):
	def __init__(self, inputList):
		self.inputList = inputList
		self.rawArguments = []
		self.command = self.parseCommand(inputList)
		self.arguments = self.parseArguments()

	def argInCommands(self, arg, commandDict):
		# This logical crazyness is to get actual True/False values.
		return None != commandDict['commands'].get(arg, None)

	def argInSubcommands(self, arg, commandDict):
		# This logical crazyness is to get actual True/False values.
		return None != commandDict['subcommands'].get(arg, None)

	def parseCommand(self, inputList):
		i = 0
		tempCommandsDict = commands
		while i < len(inputList) and self.inputList[i][0] != '-':
			arg = inputList[i]
			# Itterates through the items until it starts with a '-'
			# or until the item matches an entry in that sections 'commands' dict
			if self.argInCommands(arg, tempCommandsDict):
				# This means the argument IS a client endpoint. Break out of the loop now
				self.rawArguments = inputList[i:]
				return tempCommandsDict['commands'][arg]
			if self.argInSubcommands(arg, tempCommandsDict):
				# This means the argument IS listed in the subcommands section
				tempCommandsDict = tempCommandsDict['subcommands'][arg]
				i += 1
				continue
			# This means the argument was in neither the commands nor subcommands section
			print "Invalid command '%s'." % arg
			break

		# Reaching this point means no client endpoint was found.
		if len(tempCommandsDict['commands'].keys()) > 0:
			print '\nAvailable commands:'
			for i in tempCommandsDict['commands']:
				print ' *  %s' % i
		if len(tempCommandsDict['subcommands'].keys()) > 0:
			print '\nAvailable subcommands:'
			for i in tempCommandsDict['subcommands']:
				print ' *  %s' % i
		sys.exit(2)

	def parseArguments(self):
		i = 0
		argumentsDict = {}
		while i < len(self.inputList) and self.inputList[i][0] != '-':
			i += 1
		while i < len(self.inputList) and self.inputList[i][0] == '-':
			# Strip the dashes off the front of the keyword
			if self.inputList[i][:2] == '--':
				key = self.inputList[i][2:]
			else:
				key = self.inputList[i][1:]
			# Determine of the value is in the same element
			if '=' in key:
				value = key.split('=')[1]
				key = key.split('=')[0]
				i += 1
			else:
				value = self.inputList[i + 1]
				i += 2
			argumentsDict[key] = value
		if argumentsDict == {}:
			return None
		else:
			return argumentsDict

def displayOutput(outputDict):
	if outputDict['value'] != 0:
		sys.stderr.write("\n".join(outputDict['message'])+"\n")
		sys.exit(outputDict['value'])
	if len(outputDict['content']) > 0:
		outputTable = PrettyTable(output['content'][0].keys())
		outputTable.padding_width = 1
		for i in outputDict['content']:
			outputTable.add_row(i.values())
		print outputTable

if __name__ == "__main__":
	commands = {
		"commands": {},
		"subcommands": {
			"organization": {
				"commands": {
					"add": OrganizationAdd,
					"del": OrganizationDel,
					"set": OrganizationSet,
					"get": OrganizationGet
				},
				"subcommands": {}
			},
			"user": {
				"commands": {
					"add": UserAdd,
					"del": UserDel,
					"set": UserSet,
					"get": UserGet
				},
				"subcommands": {}
			},
			"scoringengine": {
				"commands": {
					"add": ScoringEngineAdd,
					"del": ScoringEngineDel,
					"set": ScoringEngineSet,
					"get": ScoringEngineGet
				},
				"subcommands": {}
			},
			"competition": {
				"commands": {
					"add": CompetitionAdd,
					"del": CompetitionDel,
					"set": CompetitionSet,
					"get": CompetitionGet
				},
				"subcommands": {
					"team": {
						"commands": {
							"add": CompetitionTeamAdd,
							"del": CompetitionTeamDel,
							"set": CompetitionTeamSet,
							"get": CompetitionTeamGet
						},
						"subcommands": {}
					},
					"score": {
						"commands": {
							"add": CompetitionScoreAdd,
							"del": CompetitionScoreDel,
							"set": CompetitionScoreSet,
							"get": CompetitionScoreGet
						},
						"subcommands": {}
					},
					"inject": {
						"commands": {
							"add": CompetitionInjectAdd,
							"del": CompetitionInjectDel,
							"set": CompetitionInjectSet,
							"get": CompetitionInjectGet
						},
						"subcommands": {}
					},
					"injectresponse": {
						"commands": {
							"add": CompetitionInjectResponseAdd,
							"del": CompetitionInjectResponseDel,
							"set": CompetitionInjectResponseSet,
							"get": CompetitionInjectResponseGet
						},
						"subcommands": {}
					},
					"incident": {
						"commands": {
							"add": CompetitionIncidentAdd,
							"del": CompetitionIncidentDel,
							"set": CompetitionIncidentSet,
							"get": CompetitionIncidentGet
						},
						"subcommands": {}
					},
					"incidentresponse": {
						"commands": {
							"add": CompetitionIncidentResponseAdd,
							"del": CompetitionIncidentResponseDel,
							"set": CompetitionIncidentResponseSet,
							"get": CompetitionIncidentResponseGet
						},
						"subcommands": {}
					}
				}
			}
		}
	}

	# cli format:
	# ./cssef-cli [COMMAND] [ARGUMENTS]
	config = Configuration('/etc/cssef/cssef.conf')
	argparse = ArgumentParser(sys.argv[1:])
	commandInstance = argparse.command(getConn(config))
	if argparse.arguments:
		output = commandInstance.execute(**argparse.arguments)
	else:
		output = commandInstance.execute()
	displayOutput(output)